// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "WhisKey",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(name: "WhisKey", targets: ["WhisKeyApp"]),
        .library(name: "WhisKeyCore", targets: ["WhisKeyCore"]),
    ],
    targets: [

        // MARK: - CWhisper — C/C++ target wrapping whisper.cpp
        // Source files are copies from Vendor/whisper.cpp (build artifacts, not tracked).
        .target(
            name: "CWhisper",
            path: "CWhisper",
            exclude: [
                // Metal shader source — compiled into the default library at runtime via MTLDevice
                "ggml-metal/ggml-metal.metal",
                // x86 arch files — this build targets arm64 only
                "ggml-cpu/arch/x86",
                // loongarch / riscv / s390 / powerpc / wasm arch dirs (not copied, list for clarity)
            ],
            publicHeadersPath: "include",
            cSettings: [
                .define("GGML_USE_METAL"),
                // GGML_METAL_EMBED_LIBRARY disabled for MVP — requires pre-compiled .metallib blob
                // .define("GGML_METAL_EMBED_LIBRARY"),
                // WHISPER_USE_COREML intentionally omitted — requires compiled .mlmodelc
                .define("NDEBUG"),
                // Version strings generated by CMake in a normal build; stub them here.
                .define("GGML_VERSION", to: "\"0.9.8\""),
                .define("GGML_COMMIT", to: "\"unknown\""),
                .define("WHISPER_VERSION", to: "\"1.8.4\""),
                // ggml-metal .m files use manual reference counting
                .unsafeFlags(["-fno-objc-arc"]),
                // Prevent ggml-metal-device.m from using SWIFTPM_MODULE_BUNDLE
                // (C targets don't have bundled resources; metal shader loads from bin dir)
                .unsafeFlags(["-USWIFT_PACKAGE"]),
                // Header search paths — relative to the CWhisper target root
                .headerSearchPath("."),
                .headerSearchPath("include"),
                .headerSearchPath("ggml-cpu"),
                .headerSearchPath("ggml-metal"),
            ],
            cxxSettings: [
                .define("GGML_USE_METAL"),
                // GGML_METAL_EMBED_LIBRARY disabled for MVP — requires pre-compiled .metallib blob
                // .define("GGML_METAL_EMBED_LIBRARY"),
                // WHISPER_USE_COREML disabled for MVP
                .define("NDEBUG"),
                .define("GGML_VERSION", to: "\"0.9.8\""),
                .define("GGML_COMMIT", to: "\"unknown\""),
                .define("WHISPER_VERSION", to: "\"1.8.4\""),
                .headerSearchPath("."),
                .headerSearchPath("include"),
                .headerSearchPath("ggml-cpu"),
                .headerSearchPath("ggml-metal"),
            ],
            linkerSettings: [
                .linkedFramework("Accelerate"),
                .linkedFramework("CoreML"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedFramework("Foundation"),
            ]
        ),

        // MARK: - WhisKeyCore — all business logic
        .target(
            name: "WhisKeyCore",
            dependencies: ["CWhisper"],
            path: "Sources/WhisKeyCore",
            swiftSettings: [
                .unsafeFlags(["-strict-concurrency=complete"])
            ]
        ),

        // MARK: - WhisKeyApp — menu bar executable
        .executableTarget(
            name: "WhisKeyApp",
            dependencies: ["WhisKeyCore"],
            path: "Sources/WhisKeyApp"
        ),

        // MARK: - Tests
        .testTarget(
            name: "WhisKeyCoreTests",
            dependencies: ["WhisKeyCore"],
            path: "Tests/WhisKeyCoreTests"
        ),
    ],
    swiftLanguageVersions: [.v5],
    cxxLanguageStandard: .cxx17
)
